document.addEventListener('DOMContentLoaded', function() {
    let questions = 10;
    let questionsLeft = ' [' + questions + ' questions left]';
    let names = prompt('Please give a name' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let adj1 = prompt('Please give an adjective ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let color = prompt('Please give a color' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let verb1 = prompt('Please give a verb ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let place1 = prompt('Please give a place ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let adj2 = prompt('Please give a adjective ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let ability = prompt('Please give a special ability ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let verb2 = prompt('Please give a verb ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let item = prompt('Please give an item ' + questionsLeft);
    questions -= 1;
    questionsLeft = ' [' + questions + ' questions left]';
    let place2 = prompt('Please give a place ' + questionsLeft);
  
    alert('All done! Ready for the message?');
    let sentence = "<h2>In ancient China, there was a dragon named " + names + ".";
    sentence += ' The dragon is ' + adj1 + ' and is covered in shiny ' + color + ' scales.';
    sentence += ' Whenever it ' + verb1 + ' takes a light step, the whole ' + place1 + ' will boil. ';
    sentence += ' It has a pair of ' + adj2 + ' eyes that seem to see everything. '; 
    sentence += ' According to legend, it possesses ' + ability + ' and';
    sentence += ' can ' + verb2 + ' ' + item + ' throughout ' + place2 + '. </h2>';
    document.getElementById('story').innerHTML = sentence;
  });